# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/home/john2/Documents/CtrlrX;/home/john2/Documents/CtrlrX")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/john2/Documents/CtrlrX/Packaging/Linux/postinst;/home/john2/Documents/CtrlrX/Packaging/Linux/postrm-deb")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "MIDI Control Surface Framework & Editor
 With CtrlrX, control any MIDI enabled hardware: synthesizers, drum machines, effects and samplers. Create custom user interfaces for your favorite MIDI devices, and host them as VST or AU plugins in your favorite DAW, or run them as standalone software.")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/damiensellier/CtrlrX")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "CtrlrX Team <https://github.com/damiensellier/CtrlrX>")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "sound")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CtrlrX built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/john2/Documents/CtrlrX;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/john2/Documents/CtrlrX/cmake")
set(CPACK_MONOLITHIC_INSTALL "ON")
set(CPACK_NSIS_DISPLAY_NAME "ctrlrx 8.43")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "ctrlrx 8.43")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/john2/Documents/CtrlrX/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "CtrlrX Team <https://github.com/damiensellier/CtrlrX>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "With CtrlrX, control any MIDI enabled hardware: synthesizers, drum machines, effects and samplers. Create custom user interfaces for your favorite MIDI devices, and host them as VST or AU plugins in your favorite DAW, or run them as standalone software.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MIDI Control Surface Framework & Editor")
set(CPACK_PACKAGE_FILE_NAME "ctrlrx-8.43-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/damiensellier/CtrlrX")
set(CPACK_PACKAGE_ICON "/home/john2/Documents/CtrlrX/Source/Resources/Icons/ctrlrx_logo.svg")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "ctrlrx 8.43")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ctrlrx 8.43")
set(CPACK_PACKAGE_NAME "ctrlrx")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "CtrlrX Project")
set(CPACK_PACKAGE_VERSION "8.43")
set(CPACK_PACKAGE_VERSION_MAJOR "8")
set(CPACK_PACKAGE_VERSION_MINOR "43")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_DESCRIPTION "With CtrlrX, control any MIDI enabled hardware: synthesizers, drum machines, effects and samplers. Create custom user interfaces for your favorite MIDI devices, and host them as VST or AU plugins in your favorite DAW, or run them as standalone software.")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Multimedia")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3 and BSD")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_URL "https://github.com/damiensellier/CtrlrX")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/john2/Documents/CtrlrX/Packaging/Linux/postinst")
set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE "/home/john2/Documents/CtrlrX/Packaging/Linux/postrm-rpm")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/john2/Documents/CtrlrX;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/john2/Documents/CtrlrX/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "ctrlrx-8.43-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/john2/Documents/CtrlrX/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
