---
name: Pamplejuce
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false
      build_type:
        type: choice
        description: Build type
        required: false
        default: Release
        options:
          - Release
          - RelWithDebInfo
          - Debug
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request: null

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: ${{ github.event.inputs.build_type || 'Release' }}
  BUILD_DIR: build
  PRODUCT_NAME: CtrlrX
  PROJECT_NAME: CtrlrX
  DISPLAY: :0
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_MULTIARCH: 1
  IPP_DIR: C:\Program Files (x86)\Intel\oneAPI\ipp\latest\lib\cmake\ipp

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    if: "github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name"
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      HAVE_MACOS_SIGNING_SECRETS: ${{ secrets.DEV_ID_COMBO_CERT != '' &&
        secrets.DEV_ID_COMBO_PASSWORD != '' && secrets.DEVELOPER_ID_APPLICATION
        != '' && secrets.DEVELOPER_ID_INSTALLER != '' &&
        secrets.NOTARIZATION_USERNAME != '' && secrets.NOTARIZATION_PASSWORD !=
        '' && secrets.TEAM_ID != '' }}
      HAVE_AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET != '' }}
      HAVE_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY != '' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
            pluginval-binary: ./pluginval
            extra